#!/bin/bash
# Change to LF
if [ ! -f ./mods.txt ]; then
	echo "No mods.txt file! Stopping bash..."
	exit 1
fi

if [ ! -f ./mods_regular.txt ]; then
	echo "No mods_regular.txt file! Stopping bash..."
	exit 1
fi

echo verifying mods.txt and mods_regular.txt first...
while read line; do echo $line >> mods_verified.txt; done < mods.txt
while read line; do echo $line >> mods_verified.txt; done < mods_regular.txt
tr -d "$'\r'" < mods_verified.txt > mods_verified2.txt
cut -f1 -d " " < mods_verified2.txt > mods_verified3.txt

echo removing the stupid duplications that happen
while read line; do
	if [ -d  ./@$line/$line ]; then
		rm -rf ./@$line/$line
	fi
done < mods_verified3.txt

rm mods_verified.txt mods_verified2.txt mods_verified3.txt

echo now sync and verify if it worked!